remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Real Time Virtual Prototypes
description: A model exchange format for 3D coupled multi-domain simulation of power semiconductors.
